# Generated by Django 4.1.3 on 2022-11-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.CharField(blank=True, max_length=255, null=True)),
                ('game_url', models.CharField(blank=True, max_length=255, null=True)),
                ('last_score', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
            },
        ),
        migrations.AlterModelOptions(
            name='candy',
            options={'verbose_name': 'Candy', 'verbose_name_plural': 'Candies'},
        ),
        migrations.AlterModelOptions(
            name='tgclient',
            options={'verbose_name': 'TG Client', 'verbose_name_plural': 'TG Clients'},
        ),
    ]
